import type { StreamTemplate } from "@/lib/templates/types";

/** Inspirado en plantilla_1: diamante 9 pos, roster izq, cards abajo, webcams der */
export const STREAMER_FIELD_MLB: StreamTemplate = {
  id: "streamer-field-mlb",
  name: "Streamer campo MLB",
  sport: "mlb",
  description: "9 posiciones campo, roster vertical, pitcher/batter cards, webcams",
  theme: { accentHome: "#1a5cff", accentAway: "#ff7a00", accentGold: "#c9a227" },
  positions: {
    "roster-panel": { left: "12px", top: "140px" },
    "roster-widget": { left: "20px", top: "148px" },
    "field-positions-widget": { left: "480px", top: "80px" },
    "field-cf": { left: "860px", top: "120px" },
    "field-lf": { left: "620px", top: "200px" },
    "field-rf": { left: "1100px", top: "200px" },
    "field-ss": { left: "720px", top: "280px" },
    "field-2b": { left: "1000px", top: "280px" },
    "field-p": { left: "860px", top: "360px" },
    "field-3b": { left: "620px", top: "440px" },
    "field-1b": { left: "1100px", top: "440px" },
    "field-c": { left: "860px", top: "520px" },
    scoreboard: { left: "480px", top: "16px" },
    "matchup-widget": { left: "320px", top: "720px" },
    "card-pitcher": { left: "280px", top: "740px" },
    "card-batter": { left: "720px", top: "740px" },
    "webcam-main": { left: "1240px", top: "40px" },
    "webcam-secondary": { left: "1380px", top: "560px" },
    "bases-widget": { left: "1080px", top: "640px" },
    "play-ticker": { left: "280px", top: "980px" },
  },
  elements: {
    "roster-panel": { width: "260px", height: "560px" },
    "webcam-main": { width: "640px", height: "480px" },
    "webcam-secondary": { width: "500px", height: "380px" },
    "card-pitcher": { width: "400px", height: "200px" },
    "card-batter": { width: "400px", height: "200px" },
    "field-cf": { width: "140px", height: "56px" },
    "field-p": { width: "140px", height: "56px" },
  },
  visibility: {
    scoreboard: true,
    "roster-panel": true,
    "roster-widget": true,
    "field-positions-widget": true,
    "field-cf": true,
    "field-lf": true,
    "field-rf": true,
    "field-ss": true,
    "field-2b": true,
    "field-p": true,
    "field-3b": true,
    "field-1b": true,
    "field-c": true,
    "matchup-widget": true,
    "card-pitcher": true,
    "card-batter": true,
    "webcam-main": true,
    "webcam-secondary": true,
    "bases-widget": true,
    "line-score": false,
    "play-ticker": true,
  },
};
