import type { StreamTemplate } from "@/lib/templates/types";

/** Inspirado en Plantilla_2: roster izq, cancha centro, scorebug abajo, webcam der */
export const STREAMER_FIELD_NBA: StreamTemplate = {
  id: "streamer-field-nba",
  name: "Streamer campo NBA",
  sport: "nba",
  description: "Roster vertical, posiciones en cancha, scorebug con timeouts, panel webcam",
  theme: { accentHome: "#1a5cff", accentAway: "#ff7a00", accentGold: "#c9a227" },
  positions: {
    "roster-panel": { left: "16px", top: "100px" },
    "quinteto-widget": { left: "24px", top: "108px" },
    "court-positions-widget": { left: "380px", top: "200px" },
    "court-home-pg": { left: "720px", top: "520px" },
    "court-home-sg": { left: "520px", top: "420px" },
    "court-home-sf": { left: "920px", top: "420px" },
    "court-home-pf": { left: "520px", top: "620px" },
    "court-home-c": { left: "720px", top: "680px" },
    "court-away-pg": { left: "720px", top: "280px" },
    "court-away-sg": { left: "520px", top: "320px" },
    "court-away-sf": { left: "920px", top: "320px" },
    "court-away-pf": { left: "520px", top: "220px" },
    "court-away-c": { left: "720px", top: "180px" },
    "nba-scorebug": { left: "420px", top: "820px" },
    "destacado-widget": { left: "24px", top: "780px" },
    "card-jugador": { left: "24px", top: "780px" },
    "webcam-panel": { left: "1280px", top: "48px" },
    "social-footer": { left: "0px", top: "1020px" },
  },
  elements: {
    "roster-panel": { width: "300px", height: "520px" },
    "webcam-panel": { width: "600px", height: "920px", borderRadius: "4px" },
    "nba-scorebug": { width: "1080px" },
    "court-home-pg": { width: "120px", height: "80px" },
    "court-away-pg": { width: "120px", height: "80px" },
    "social-footer": { width: "1920px", height: "48px" },
  },
  visibility: {
    "nba-scorebug": true,
    "quinteto-widget": true,
    "roster-panel": true,
    "court-positions-widget": true,
    "court-home-pg": true,
    "court-home-sg": true,
    "court-home-sf": true,
    "court-home-pf": true,
    "court-home-c": true,
    "court-away-pg": true,
    "court-away-sg": true,
    "court-away-sf": true,
    "court-away-pf": true,
    "court-away-c": true,
    "destacado-widget": true,
    "card-jugador": false,
    "webcam-panel": true,
    "social-footer": true,
  },
};
